def find_letters(s):
	t = 0
	a = 0
	g = 0
	c = 0
	for ch in s:
		if ch == 'C':
			c = c + 1
		elif ch == 'T':
			t = t + 1
		elif ch == 'A':
			a = a + 1
		elif ch == 'G':
		    g = g + 1
	return str(a) + " " + str(c) + " " + str(g) + " " + str(t)

print(find_letters("GTTTCCTTGCGCACTAAGCACAGAGAAAGCATAAGCGAACGAAAGCAGACGCATCTCTGCTTCAGTGCGAGGATCTACGGTTGGTTCACCGCGCATCCTCGTTTTGAAACGTCATCGGGCTTCCCCCTAGCAGAAAAGGATCCTTAGGGTGAAATGACAAACTGCGACCTGCACCCTCCAGACCCAGATATCTCGGTACTAGCTCTTGCGGCACTCCAACCTGGATGGCTCAGTACGCTGTAGAGGGTGGGCTGGAAGCACGAGTTGCATAATAAGACTCTGAGCGGGCACGACTTTGAGCGAAACTTGGCCACTCCTAACGTAAGGATAATCTTTAGGCGGATTCCACTTGAAGCAAGTGCCAAGTAGTGACAGTGGTACGACGCTTTTTGGGTAATTCGAATGTCGGACGTGGTTCTTTACAATAGGAACCCTATTTATCTGGATGATGTCCCGAATTTGGGGCAGCCGCAAATTACGTGAGCCTTTCGGTTCACGGTGGATAGCCATAAAGCAGGCCCAGTATGCCGGCCGAGAACGAGAATCGTCCAGAGGTGAAGTGGTTTCCGCGCCTAGCGTCGTTTTAGGCGTATTGGCCGACAACTTAGCAGTAAAACGTTGGAGTACTAAGTGCGTTAACATTATACGTATTCGTGGCCTTATGTTGTGATCAGGCATGGAACCGTTCTCATGCTATAAAGGGGGAGTGATTAGATCGCAACCAAACGCGCTAGCGAGGTCGTCGGGATGCCAGATGGATCATTCTGCATAGTACCAGGCGTAGAAGGGCAGTTTGACTCTTCGTACTCCGAGACAGCGACTAGTCATTGTGTGGAACATGAGTAAATAGTTATAAAGGAAAACTTTGGAGTCAGCGATACGTACACGATGAACCATTCCATTATCCATAGGACTGGAAGA"))